# Generated by Django 4.2 on 2023-10-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='record',
            new_name='student_record',
        ),
    ]
