# Generated by Django 4.2 on 2023-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_record_student_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_record',
            name='image',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', upload_to=''),
        ),
    ]
