# Generated by Django 4.2 on 2023-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_student_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_record',
            name='image',
            field=models.ImageField(default='blank-profile-picture-973460_1280.webp', upload_to=''),
        ),
    ]
