# Generated by Django 4.2 on 2024-01-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price',
        ),
        migrations.RemoveField(
            model_name='card',
            name='unit_price',
        ),
    ]
