# Generated by Django 4.2 on 2024-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_card_price_remove_card_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='card',
            name='quantity_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=0),
        ),
    ]
